### ISSUE TITLE
Node parameters in toml file

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-cli#18]
@i1i1 this is both relevant to SDK and CLI.
In the `settings.toml`, we have this:
```toml
[node]
chain = "gemini-2a"
execution = "wasm"
blocks_pruning = 1024
state_pruning = 1024
validator = true
name = "NODE_NAME"
port = 30333
unsafe_ws_external = true # not sure we need this
```

How should we translate these information to SDK's node methods?
```rust
    let node: Node = Node::builder()
        .mode(NodeMode::Full)
        .name(node_name)
        .build(node_directory, chain_spec::gemini_2a().unwrap())
        .await
        .expect("error building the node");
```

We either change the contents for node in `settings.toml`, or make some changes in SDK side.

The problems:
- `chain_spec` does not accept a string in SDK
- `NodeMode` does not 100% corresponds to -> `blocks_pruning = 1024, state_pruning = 1024, validator = true`
- no `execution` field in SDK
- I don't know about this: `port = 30333`
- and this: `unsafe_ws_external = true # not sure we need this`

What is your take on these?
