### ISSUE TITLE
setting plot size to an invalid size prevents `wipe`

### ISSUE THREAD

**Issue by achiurizo** [subspace/subspace-cli#59]
When I modify my `settings.toml` to an invalid size, this prevents the `subspace-cli wipe` command from working. Here's an example:

```toml
[farmer]
address = 'ADDRESS'
plot_directory = '/home/achiurizo/.local/share/subspace-cli/plots'
plot_size = '10 MB' # offending change here
opencl = false

[node]
chain = 'dev'
execution = 'wasm'
blocks_pruning = 1024
state_pruning = 1024
role = 'Full'
name = 'achiurizo'
listen_addresses = []
rpc_method = 'Auto'
force_authoring = false

[chains]
dev = 'that local node experience'
```

While `subspace init` does prevent me from initially setting an incorrect plot size, it's entirely possible that I can modify the `settings.toml` after. We should still be able to `wipe` regardless of that change.
